### ISSUE TITLE
Reported wind speed is higher than actual

### ISSUE THREAD

**Issue by tvtechdir** [alexander0042/pirate-weather-ha#16] opened 2021-09-20 18:41 UTC
Residing in Central Ohio, USA here. The wind speed is being reported in the low 40mph range, but is actually much much lower (I fly drones which is I'm noticing).

**Comment by alexander0042** [comment] 2021-09-20 19:10
Hi,

Thanks for opening an issue- weather data glitches are the most interesting (and important) bugs, so I really appreciate the feedback! 

Do you get the same results from the web UI (https://weather.pirateweather.net/) as the raw API? I'm not seeing anywhere in the US that should be returning anything close to that (https://www.tropicaltidbits.com/analysis/models/?model=hrrr&region=us&pkg=mslp_wind&runtime=2021092018&fh=1), so I'm wondering if there's something funny with the lat lon conversion here? 

If you want to send me an e-mail with your exact location and a screenshot, that would help troubleshoot this: api@alexanderrey.ca

Thanks,
Alexander

**Comment by tictocdoc** [comment] 2021-10-30 19:16
I am seeing that too on 10/30/32.  Wind is actually dead calm but the wind speed shown is 15.271 mph, bearing 304.99.  Any updates on this?

**Comment by alexander0042** [comment] 2021-10-30 21:26
Hi,

thanks for the report! Short answer is no update yet, but longer one is more promising. 

The issue I’m having with these reports is that it’s tricky to diagnose the root cause, since I can’t easily go back and see what the input model data from NOAA was that led to these outputs. I spent some time thinking about this, and I think the best option is to retain the input data for a couple weeks, which will make debugging way easier! I’ve started working on the code to do that, and hoping to have it done in the next couple weeks. 

In the meantime, could you let me know roughly what location this occurred at (either here or at api@alexanderrey.ca)? If you’re in the continental US or southern Canada, I can look at the inputs to see what might be happening!

**Comment by cloneofghosts** [comment] 2021-11-10 18:23
I'm currently seeing this right now in Nepean which wouldn't be affected by the Ottawa River. I'm seeing 50 km/h on the website and the API compared to 22 at the airport.

**Comment by tvtechdir** [comment] 2021-11-10 18:27
If you have access to wind speeds at varying altitudes (like a drone weather stats site or app) see if the incorrect wind speed is occurring at a certain altitude other than ground level or is the gust reading. The latter seemed to be one of my location's contributing problems.

**Comment by cloneofghosts** [comment] 2021-11-10 21:10
The gusts at the time said 36 km/h so I don't think it was showing the gusts. I wonder if it's falling back to the wind speed at a different altitude if the one at ground level (or whatever the one pirateweather uses) isn't available. That could be why it happens sometimes and then fixes itself.

**Comment by NCC1941** [comment] 2021-11-12 01:50
Just chiming in to note that I'm seeing the same issue as well. Reported wind speed of 106mph this morning, which is amusing. I'd have noticed if that were true! And it just now spiked to 67mph, also amusingly incorrect. I've only been using Pirate Weather for a day or so (thank you so much, by the way!), but so far none of the other weather stats have been noticeably off.

**Comment by alexander0042** [comment] 2021-11-14 19:58
Thanks for the reports here everyone, they really help to troubleshoot what’s happening! 

I dug into this a little more this weekend, and it doesn’t seem to be an issue with guests, but the elevation seems to be closer to the  root of the problem. The main issue is the I’m using the low resolution version of the GFS weather model to fit within the Lambda limitations, so sometimes it’s grabbing wind speeds from nearby lakes/ mountains/ whatever. 

This has been an issue for a while, but has sort of stumped me, since Lambda has a hard 500 mb temp storage cap. However, I think I have a solution now (using Fargate for processing instead). Hoping to implement this in the next couple weeks, so I’m hopeful that this fixes it! 

Thanks for keeping me posted with how these winds keep looking, and we’ll get to the bottom of this 💨

**Comment by alexander0042** [comment] 2022-01-11 14:08
So with the V1.0 release, the wind speed problem is (finally) solved, so I'm going to close this issue for now. Keep an eye on things though, and definitely let me know if anything else crops up!

**Closed by alexander0042** 2022-01-11 14:08 UTC
Labels: bug

**Comment by tvtechdir** [comment] 2022-01-11 14:15
Your work here is fantastic. I saw your email regarding the 1.0 release and checked out the new wind speed maths. Looks like it’s taking the measurement from an altitude of 100 feet. Home assistant is now running Pirate Weather full time!
