### ISSUE TITLE
`is_metric` property of unit system is deprecated. [2022.11 onwards]

### ISSUE THREAD

**Issue by GuyKh** [alexander0042/pirate-weather-ha#60] opened 2022-11-03 07:41 UTC
```
[homeassistant.helpers.frame] 
Detected integration that accesses the `is_metric` property of the unit system. 
This is deprecated and will stop working in Home Assistant 2023.1. 
Please adjust to use instance check instead.. 
Please report issue to the custom integration author for pirateweather using this method at custom_components/pirateweather/weather.py, line 96: units = "si" if hass.config.units.is_metric else "us"
```

In here:
https://github.com/alexander0042/pirate-weather-ha/blob/master/custom_components/pirateweather/weather.py#L96

**Comment by smarthomefamilyverrips** [comment] 2022-11-03 11:12
Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for pirateweather using this method at custom_components/pirateweather/sensor.py, line 498: elif hass.config.units.is_metric:
Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for pirateweather using this method at custom_components/pirateweather/weather.py, line 96: units = "si" if hass.config.units.is_metric else "us"

**Comment by alexander0042** [comment] 2022-11-03 12:57
Thanks for using this integration and opening this issue! The good news here is that this is fixed in the new version (along with adding a UI config flow and a bunch of other improvements). If you'd like to help test it out, the instructions are in this thread: <https://github.com/alexander0042/pirate-weather-ha/issues/57>. Otherwise, the new version should be pushed out in about a month

**Comment by DaN66O** [comment] 2022-12-18 10:40
Thank you for your work.
When can I expect a new version with warning fixes ?

**Comment by alexander0042** [comment] 2022-12-21 18:41
Today! Just pushed the update and no warnings on my end, so hopefully everything is resolved.

**Comment by smarthomefamilyverrips** [comment] 2022-12-21 19:00
> Today! Just pushed the update and no warnings on my end, so hopefully everything is resolved.

Not see update yet 😕

**Comment by alexander0042** [comment] 2022-12-21 19:06
That's weird, since it's showing up on my end. I only released it about an hour ago though, so maybe just needs some time to propogate

**Comment by smarthomefamilyverrips** [comment] 2022-12-21 19:15
@alexander0042 did came and did the update, but with the update also came a new warnings in log

1.This error originated from a custom integration.

Logger: custom_components.pirateweather
Source: custom_components/pirateweather/__init__.py:106
Integration: Pirate Weather (documentation, issues)
First occurred: 21:09:55 (1 occurrences)
Last logged: 21:09:55

An existing weather coordinator already exists for this location. Using that one instead

2.
This error originated from a custom integration.

Logger: custom_components.pirateweather.weather
Source: custom_components/pirateweather/weather.py:140
Integration: Pirate Weather (documentation, issues)
First occurred: 21:09:55 (1 occurrences)
Last logged: 21:09:55

Configuration of Pirate Weather (weather entity) in YAML is deprecated Your existing configuration has been imported into the UI automatically and can be safely removed from your configuration.yaml file

3.
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:374
Integration: Sensor (documentation, issues)
First occurred: 21:10:34 (1 occurrences)
Last logged: 21:10:34

The unit of sensor.pirateweather_precip_intensity (in) can not be converted to the unit of previously compiled statistics (mm/h). Generation of long term statistics will be suppressed unless the unit changes back to mm/h or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

**Comment by alexander0042** [comment] 2022-12-21 19:20
2/3 of these aren't actually aren't issues, so maybe I need to change how they're logged. The first is just a heads up that the integration is using data from another integration, which is the expected behavior. The second is saying that you can remove the lines for Pirate Weather from your configuration.yaml. The third one is more of an issue- does your configuration.yaml include a requested unit?

**Comment by smarthomefamilyverrips** [comment] 2022-12-21 19:25
I did take away all off pirateweather in my config so I not think I have any requested unit, but also if I did delete all of pirateweather in my config.yaml why still get message that can he deleted.... also if I check integration in UI now I have 2 times pirateweather, 1 with 8 entities and 1 with 1 entitie

**Comment by alexander0042** [comment] 2022-12-21 19:31
Ok, sorted out the unit issue and committed the change! I'm going to see if anything else comes up today before pushing v1.01, but I'll put that update in tomorrow. The other yaml config warning should appear on the first restart, but shouldn't appear on any restart after it's been removed. 

The two items are a product of having both weather an sensor blocks, and there's no way around that sadly. If this is an issue, you could create a new sensor using the GUI and it should be resolved

**Comment by smarthomefamilyverrips** [comment] 2022-12-21 19:31
@alexander0042 I still had some pirateweather related lines in my config.yaml, after deleting these warning 2 and 3 disappeared, warning 1 still stays after restart of HA

**Comment by smarthomefamilyverrips** [comment] 2022-12-21 19:53
@alexander0042 after deleting both of the integrations in UI and add a new one also warning message 1 did disappear at me, and I also did make the change/commit in the sensor.py file, for now at restart I am without any warning messages ☺️

**Comment by alexander0042** [comment] 2023-01-06 14:49
Since everything seems to be working now, I'm going to go ahead and close this issue. I've also pushed an update that clarify the error messages, which should help to avoid this issue in the future. Thanks again for opening this and troubleshooting with me, and feel free to open a new issue if anything else comes up

**Closed by alexander0042** 2023-01-06 14:49 UTC
