### ISSUE TITLE
No card type found

### ISSUE THREAD

**Issue by NVader2000** [alexander0042/pirate-weather-ha#28] opened 2021-12-14 11:39 UTC
Just installed. What am I missing?

HA versions:
Core: 2021.12.1
Super: 2021.12.1
Host: 7.0

**Comment by alexander0042** [comment] 2021-12-14 11:45
Hi, thanks for checking this project out!

Happy to help here, just need a little more information- did you install this via HACS? I'm also guessing you're seeing an error in the logs, do you mind sending the full text of the error?

**Comment by NVader2000** [comment] 2021-12-14 11:52
Installed from HACS. Logs from Supervisor or Core? If the former there are no errors.

**Comment by alexander0042** [comment] 2021-12-14 12:10
Wherever the error is cropping up (based on the name of this issue) would be great! I thought it might be a problem with the 2021.12 update, but I just updated my test system to that and everything seems to be working ok, so that's probably not it

**Comment by NVader2000** [comment] 2021-12-14 12:14
![image](https://user-images.githubusercontent.com/34590572/145996257-7da574e8-458c-4a6a-8095-e2022bf71b02.png)

**Comment by alexander0042** [comment] 2021-12-14 12:15
Oh, interesting! I'd never tried using the GUI config editor, but let me give that a go and see if I can reproduce/ resolve this

**Comment by alexander0042** [comment] 2021-12-14 12:20
Sorry about this, but I'm a little lost here. Where in the Home Assistant interface is that screenshot from, since I can't seem to find it?

**Comment by NVader2000** [comment] 2021-12-14 12:24
Overview> Add Card> Manual (at the very bottom).

**Comment by NVader2000** [comment] 2021-12-14 12:26
FYI: I did try the manual way as well. Same error.

**Comment by alexander0042** [comment] 2021-12-14 12:37
Ok, got it, and learned something in the process, since I've never added a manual card before. If you're using the automatic dashboard, then the card should show up automatically, but I should have this method documented somewhere. 

To get the card to show up, you need to use these two lines:
```
type: weather-forecast
entity: weather.pirateweather
```

This creates a "Weather" type card, using PirateWeather as the source. Separately, in your `configuration.yaml`, you need to drop in the text you have there (Latitude, Longitude, API, etc.). The `configuration.yaml` defines the integration (aka the python script that fetches the data from my API), and then the card is what displays it. Hence the two different spots here

**Comment by NVader2000** [comment] 2021-12-14 15:58
That does not seem to work.

![image](https://user-images.githubusercontent.com/34590572/146004406-a070ccb3-c934-484d-902d-42085c237622.png)

**Comment by alexander0042** [comment] 2021-12-14 16:05
Great point- there's a specific order here:
1. Update your `configuration.yaml` with the PirateWeather integration
2. Restart Home Assistant Core
3. Add in the manual weather card

**Comment by NVader2000** [comment] 2021-12-15 01:20
Ok still not working. Let me see if I understand this correctly. I have HACS, do I add PriateWeather from there, then update my configuration.yaml with the following?

weather:
  - platform: pirateweather
    api_key: <APIKEY>
    # Additional optional values:
    latitude: Location latitude
    longitude: Location longitude
    mode: "hourly" (default) or "daily"
    name: Custom name
    

# you can also get a sensor data
sensor:
  - platform: pirateweather
    api_key: <APIKEY>
    scan_interval: '00:15:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

Then restart 'Core' and then add a custom card from Overview> Add Card and past in the following?

![image](https://user-images.githubusercontent.com/34590572/146105132-ac5356bc-77a2-4073-b3ae-394f96575b9f.png)

**Comment by alexander0042** [comment] 2021-12-15 01:43
Hmm, if it's in your configuration.yaml, it should show up? Are you seeing any errors in your HA core logs?

**Comment by alexander0042** [comment] 2021-12-15 01:47
Should look something like this:
![image](https://user-images.githubusercontent.com/26213938/146107856-b62971d6-8e92-4bb6-8315-74f3cda30a06.png)

**Comment by NVader2000** [comment] 2021-12-15 02:14
I am adding this to the configuration.yaml, then reboot 'Core'.

![image](https://user-images.githubusercontent.com/34590572/146110376-d4cb8b8c-195b-4b54-983b-2704c1eaa799.png)

but when I do I get this,

![image](https://user-images.githubusercontent.com/34590572/146110502-4ee1907c-4f03-4ee7-88be-d426d96d4b2d.png)

**Comment by alexander0042** [comment] 2021-12-15 02:23
Ok, now we’re getting somewhere 😃 for whatever reason, it didn’t install from HACS, which explains all the subsequent errors. Were there any issues during the HACS install? Maybe try reinstalling it from there

**Comment by alexander0042** [comment] 2022-01-11 14:04
Any updates with this? Hopefully you got this working, and I can go ahead and close this issue

**Closed** 2022-01-19 15:05 UTC
Labels: documentation
