### ISSUE TITLE
Using darksky in configuration.yaml still uses api.darksky.net

### ISSUE THREAD

**Issue by kdttocs** [alexander0042/pirate-weather-ha#32] opened 2021-12-28 00:26 UTC
"pirateweather" folder is properly named "darksky" in custom_components

Configuration.yaml set to
```
weather:
  - platform: darksky
```

In core logs I get:
`Unable to connect to Dark Sky. 403 Client Error: Forbidden for url: https://api.darksky.net/forecast/...`

**Comment by alexander0042** [comment] 2021-12-28 18:36
Hi,

Thanks for opening this issue! Quick question- did you install this using HACS, or manually? It should install as `pirateweather` as the folder name (<https://github.com/alexander0042/pirate-weather-ha/tree/master/custom_components>). If you want to "override" the built in DarkSky module, you can rename, but you have to rename the folder manually,

**Comment by crackyn** [comment] 2021-12-30 13:26
I am having the same issue. I have tried installing using hacs, and renaming the folder to darksky, I have also attempted the manual process and using the file darksky instead of pirateweather. I have also tried redirecting the call to the pirateweather apis using a host entry. the host entry just changes the error to a certificate failure.

**Comment by alexander0042** [comment] 2021-12-30 16:47
Ok, I see what's happening here! There are two issues. which complicated troubleshooting a bit:

1. I believe the `manifest.json` file needs to be updated to have a domain of `darksky` and a name of `Dark Sky`. This (presumably) helps Home Assistant keep track of what we're referring to when Dark Sky is requested.
2. This does override the built in integration, but because the custom scripts say PirateWeather everywhere, things still show up as that! To have the entity name match the built in one, change the `DEFAULT_NAME` on line 71 of [weather.py ](https://github.com/alexander0042/pirate-weather-ha/blob/master/custom_components/pirateweather/weather.py)to read `Dark Sky`! This matches the way it's setup in the default [weather.py](https://github.com/home-assistant/core/blob/dev/homeassistant/components/darksky/weather.py)

**Comment by crackyn** [comment] 2021-12-30 18:00
I'll try that when I get back to my house and let you know.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by crackyn** [comment] 2021-12-30 19:06
Confirmed, that resolves the issue.

**Comment by alexander0042** [comment] 2021-12-30 19:08
Great! I'm going to keep this one tagged as documentation to remind me to update the README to let people know this

**Comment by grantalewis** [comment] 2022-07-07 00:53
Implemented [the above fixes](https://github.com/alexander0042/pirate-weather-ha/issues/32#issuecomment-1003104744) and am now seeing this in the Home Assistant logs:

```
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:308
Integration: Weather ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: 8:47:53 PM (1 occurrences)
Last logged: 8:47:53 PM
custom_components.darksky.weather::DarkSkyWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.```

**Comment by alexander0042** [comment] 2023-05-15 19:48
Since this has been updated in the docs, I'm gong to close this for now! Feel free to re-open if anything else comes up, and thanks again for your help troubleshooting.

**Closed by alexander0042** 2023-05-15 19:48 UTC
Labels: documentation
