### ISSUE TITLE
no weather entities created 

### ISSUE THREAD

**Issue by trackhacs** [alexander0042/pirate-weather-ha#69] opened 2023-01-02 12:58 UTC
I installed via HACS and set API key. only activated weather - but here is no entitie created nor a lovelace card. only the default weather forecast from hass shows up.

any suggestion how to debug?

**Comment by trackhacs** [comment] 2023-01-02 19:37
found this in log:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/pirateweather/weather.py", line 181, in async_setup_entry
pw_weather = PirateWeather(name, unique_id, forecast_mode, weather_coordinator, outputRound)
File "/config/custom_components/pirateweather/weather.py", line 219, in __init__
self._ds_currently = self._weather_coordinator.data.currently()
AttributeError: 'NoneType' object has no attribute 'currently'

**Comment by alexander0042** [comment] 2023-01-03 13:58
Hi,

Thanks for using this integration, and apologies for the issue here! The error message was key here, and let me work out the cause of this bug- it comes from a race condition when the integration comes up before the internet does. 

As a workaround, if you select "Reload" from the integration UI, everything should come back online. I'll push a more permanent fix as soon as I work out how to get around this!

**Comment by trackhacs** [comment] 2023-01-03 23:22
reloaded - no change - same error message. 

i use core in docker - maybe this has influence?

**Comment by googanhiem** [comment] 2023-01-05 16:02
I also had the same issue, on Hass OS (no docker). 
I solved my issue by going into the api page and "subscribing" (i should have read the docs more closely but its all here https://pirateweather.net/getting-started)

**Comment by alexander0042** [comment] 2023-01-05 16:34
Thanks for posting your solution @googanhiem, I suspect that's the issue here as well. 

I'll be pushing out an update to this integration today that makes this error (and resolution) much more visible, which should hopefully help fix these issues in the future

**Comment by trackhacs** [comment] 2023-01-05 17:47
ah - ok. thats definitly not self explanatory.

so i reinstalled and put like described for the days:  0-7, but got error message below. even changing it later (to 0,1,2,3,4,5,6) within the integration setup didn't  change the error message. 

Suggest to make the description more clear, add sanity check and prefill suggestion as reference. 



```
Error setting up entry PirateWeather for pirateweather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pirateweather/__init__.py", line 86, in async_setup_entry
    forecast_days = [int(i) for i in forecast_days]
  File "/config/custom_components/pirateweather/__init__.py", line 86, in <listcomp>
    forecast_days = [int(i) for i in forecast_days]
ValueError: invalid literal for int() with base 10: '0-7'
```

**Comment by alexander0042** [comment] 2023-01-06 14:51
That's a great suggestion, and just pushed that change in the latest version (v1.02)! There's now a line of text underneath the box that clarifies the syntax, and the error messages should be clearer when something is wrong. 

To fix this issue, you may have to remove and add the integration in again unfortunately. Since it keeps hitting the error when loading the config, I don't know if it will be able to accept the corrected syntax

**Comment by chumbazoid** [comment] 2023-01-10 05:17
This integration looks great and thank you for the hard work.

However, I'm having a similar issue with no sensors created although I have subscribed to the API.

My steps:

0. Installing on Home Assistant Supervised core-2023.1.2, supervisor-2022.12.1, Debian 11
1. Confirm pirateweather.net account info. APIs subscribed and authorized:

![pf1](https://user-images.githubusercontent.com/68184533/211463991-dbc4b18c-06e2-4987-a435-372f92efcd73.png) ![pf2](https://user-images.githubusercontent.com/68184533/211464007-848e72dc-5d8e-4f21-b7d7-86d1a1f3e459.png)

2. Install HACS PW 1.02 integration. Restart HA.
3. Add and configure HA PW integration. Don't really understand the "forecast sensors in CSV" bit yet but 0,1,2,3,4,5,6 seems reasonable to start...

![Untitled-3](https://user-images.githubusercontent.com/68184533/211465237-5e5c36c2-35df-4ae5-9fc6-815ebb3f8bf9.png)

4. Click Submit. "Success! Created configuration for PirateWeather."
5. Result: 1 entity available: `weather.pirateweather`. HA Weather Card works successfully. No sensors have been created.

![Untitled-1](https://user-images.githubusercontent.com/68184533/211465753-03f441c9-22b8-43e0-9869-1558c95d8de4.png)

6. Enable debug logging on HA PW integration and restart HA.
7. Check `/usr/share/hassio/homeassistant/home-assistant.log`. Strangely(?), no information from PW except the usual HA complaint about an untested integration.
8. Lot of data in the `weather.pirateweather` entity "Info" tab but still no sensor entities...

![Untitled-1](https://user-images.githubusercontent.com/68184533/211467344-c5070f8b-885a-4138-bf64-ebeec790bbea.png)

Any help appreciated and please pardon if I'm overlooking something obvious. Thanks in advance.

**Comment by alexander0042** [comment] 2023-01-10 18:24
Since this change has been pushed out and seems to resolve things, I'm going to go ahead and close this issue. Definitely feel free to either re-open or create a new issue if anything comes up though!

**Closed by alexander0042** 2023-01-10 18:24 UTC
