### ISSUE TITLE
Sensor name doesn't act as expected and renaming creates orphans

### ISSUE THREAD

**Issue by joaldes** [alexander0042/pirate-weather-ha#63] opened 2022-12-05 01:10 UTC
I am using the precip_probability monitored condition and my app is up-to-date.  

The name of the sensor that gets created ends up as a concatenated string of 'Name' and sensor type (I think) instead of using just the 'Name'.

I set the sensor name to Zebra in my sensors.yaml file:
```
- platform: pirateweather
  name: Zebra
  api_key: 6mwfdaJRNy39nrnNIUXwXhUV7FxSmbZ8HSW9m253
  scan_interval: "00:05:00"
  monitored_conditions:
    - precip_probability
```

You can see in this screenshot, the newest sensor with 'Zebra' in the name contains more than just Zebra.  Further, renaming the sensor in the config leads to some duplicate orphan sensors:
[List of random sensors](https://i.imgur.com/eX1IQZ7.png)

Not sure what other info will be useful or what troubleshooting I can do.  Thanks!

**Comment by alexander0042** [comment] 2022-12-05 18:50
Hi,

Thanks for testing out this API/ integration and opening this issue. That definitely isn't how it should look, so something to dig into here. One quick question- are you running the HACS version of this or the UI "dev-config-flow" branch mentioned here: <https://github.com/alexander0042/pirate-weather-ha/issues/57>?

**Comment by joaldes** [comment] 2022-12-05 20:00
Hi,

Thanks for putting this together, I use this on a daily basis and is part of my morning notification!

I am using the HACS version and installed via HACS.

**Comment by alexander0042** [comment] 2022-12-05 20:07
OK, that helps to clarify things. Part of this is the expected behavior- the sensor name should be the "name" you give in the config plus the monitored condition (in this case precip_probability). I'm guessing the other orphaned ones are from putting some combination of "precip_probability" in the name field, and they should be able to be deleted. 

Are you migrating over from a Dark Sky config? One of my goals is to maintain compatibility with Dark Sky, which sometimes means that things can't work the way I'd like them to now

**Comment by joaldes** [comment] 2022-12-05 20:57
I'm not migrating from Dark Sky, but I completely understand about the interoperability issues!  

I didn't think of it before, but it does make sense to have the 'precip_probability' appended to the sensor name, since that config can contain a list of other conditions to monitor.  I didn't see that in the ReadMe on the integration page but perhaps I missed that?  If not, it might be helpful to add a note about the sensor naming scheme.

Thanks for the quick responses!

**Comment by alexander0042** [comment] 2022-12-05 21:28
Definitely need to clarify this in the documentation- I've added that to the todo list! 

You can't leave it blank, but maybe try using an empty string "" or a period "." might work here

**Comment by joaldes** [comment] 2022-12-05 22:04
Thanks, I'll poke around and see if I can get it fixed up.  Any suggestions on deleting all these other sensors that have been erroneously created?

**Comment by joaldes** [comment] 2022-12-08 05:43
Just wanted to follow up and say that the other random sensors seem to have taken care of themselves.

**Comment by alexander0042** [comment] 2022-12-21 18:40
Thanks for the update! Since it seems to have resolved itself, I'm going to close this issue for now; however, feel free to re-open or create a new issue if anything else comes up!

**Closed by alexander0042** 2022-12-21 18:40 UTC
